// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: 001_users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
Insert into users (id, created_at, updated_at, email)
Values(
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1
)
Returning id, created_at, updated_at, email
`

func (q *Queries) CreateUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const lookUpUser = `-- name: LookUpUser :one
Select id From users Where email = $1
`

func (q *Queries) LookUpUser(ctx context.Context, email string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, lookUpUser, email)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const resetUsers = `-- name: ResetUsers :exec
TRUNCATE TABLE chirps, users RESTART IDENTITY CASCADE
`

func (q *Queries) ResetUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetUsers)
	return err
}
